name: 'ci pipeline'

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore TestTaskToItKontact.sln
      working-directory: .

    - name: Build
      run: dotnet build TestTaskToItKontact.sln --no-restore --configuration
      working-directory: .

    - name: Tests
      run: dotnet test TestTaskToItKontact.sln --no-build
      working-directory: .
